services:
  # Web service
  - type: web
    name: milan-stats-dashboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
    healthCheckPath: /
    autoDeploy: true 